### ISSUE TITLE
Display a Map on property full details

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#11]
Hi Steve,

Looking through the code, there doesn't look to be a function that pulls the map out to display on the full details page, is this correct ?

https://github.com/propertyhive/WP-Property-Hive/blob/c69bcf0e7dec6f028fb97ad050bc88fcd684a14c/includes/ph-template-functions.php#L527-L537

If so, are you thinking of having this as a separate plugin or in the core ?

Thanks,
Tom

**Comment by propertyhive** [comment]
There's not. In the past I've done it bespoke on a per-site basis. 

I foresee four issues with making it part of the plugin:

1) Some sites display the map in a lightbox, some display it inline, others display it in a tab. When the map is in a lightbox or tab you need to initialise it once it's visible as opposed to on page load.
2) People often want customisation on the map (custom marker or styling).
3) What if someone already has the Google Maps API JS included on the site and we enqueue it too. You'd have two Google Maps API JS's included on the page which could cause conflict, especially if the custom one that already existed has other libraries included.
4) How do we do the change without effecting existing sites.I know this shouldn't stop features being built but it should still be considered

Due to the above I haven't even thought about if I'm honest. I'm open to suggestions if you have any thoughts on the above?

These issues also lead me to believe that doing it as a separate add on might be better but then the other part of me thinks, is it really worth doing it as a whole new plugin for such a small feature.

**Comment by CHEWX** [comment]
Ah cool, just checking, I've done it custom for now using `get_post_meta()` for the longitude and latitude - will have a think about a long term solution.

**Comment by paulormandy** [comment]
Hi CHEWX,
I'm trying to achieve the same thing.
ie: 'display a map on the full details page' - would you be able to post the solution you came up with?
Cheers

**Comment by propertyhive** [comment]
@indianred Here is an example that will hopefully put you on the right path:

https://gist.github.com/propertyhive/e437dd2465430c7cfce014f610f2f2bc

This is a basic Google map and uses the property latitude and longitude to set the map center and marker position. 

Take a look and if there's any questions just let me know.

Note: I'm assuming you are a little technical in my response above. If you're staring at this with a blank expression, feel free to get in touch with me at info@wp-property-hive.com and I'll be happy to help further.

Steve

**Comment by indianred** [comment]
Hi Steve,
Thanks for the quick response - worked liked a dream!
You're a life saver.

**Comment by propertyhive** [comment]
@indianred Glad to hear it! If there's any other questions feel free to email us or raise an issue here and we'll look ASAP.

It'd be great to see the site you've built once you've completed it :)

**Comment by propertyhive** [comment]
As this question is coming up more and more I've just put an update into version 1.1.14 (https://github.com/propertyhive/WP-Property-Hive/commit/df05f6b852c07213e54d0cec25d1e6bd799f3882) which allows you to output a map showing the properties location on the single property page.

The map can be output using a shortcode:

`[property_map]`

or with parameters such as:

`[property_map zoom="13" height="600" scrollwheel="false"]`

Alternatively, you can call the function direct like so:

`echo get_property_map();`

or with parameters:

`echo get_property_map( array( 'zoom' => '13', 'height' => '600', 'scrollwheel' => 'false' ) );`
