### ISSUE TITLE
Problem adding media floorplans and EPC

### ISSUE THREAD

**Issue by Spring279** [propertyhive/WP-Property-Hive#122]
Problem adding media floorplans and EPC. Please can this be resolved asap.

**Comment by espc-jcampbell** [comment]
Having a similar issue, only seems to be happening after the 1.4.65 update (having also updated WordPress to 5.5). Will try rolling the plugin back to see if it works.

**Comment by tomnightingale-adtrak** [comment]
Hi, 

 jQuery 1.12.4. has been included in Wordpress since 4.6 - and `live()` is not supported beyond 1.9

Searching the PropertyHive plugin, there's two calls to the `live` function in the following files:

..\plugins\propertyhive\includes\admin\post-types\meta-boxes\class-ph-meta-box-property-photos.php
..\plugins\propertyhive\includes\admin\ph-meta-box-functions.php

Consider replacing this with jQuery's `.on()` function.

**Comment by propertyhive** [comment]
Thanks for reporting, and apologies for the inconvenience. Just to confirm a new release was put out this morning at around 8am that rectifies this.

Steve
