### ISSUE TITLE
Template assistant issue

### ISSUE THREAD

**Issue by MB-sites** [propertyhive/WP-Property-Hive#152]
Hi there,

I have an issue with the template assistant. Everything was working fine and I got the layout the way I wanted, but all of a sudden the template assistant is no longer taking any effect on the front end.
The layout settings don't make any difference and also the form fields are not displaying as they should. See the attached screenshots. I have also included a screenshot of the used plugins just in case on of them could be the culprit.

The URL with properties: https://onepagewebsites.net/properties/
<img width="1680" alt="Screenshot 2021-03-18 at 16 34 56" src="https://user-images.githubusercontent.com/79659755/111663886-231b3180-8809-11eb-8d2b-12ea34f0ba1b.png">

<img width="1678" alt="Screenshot 2021-03-18 at 16 38 53" src="https://user-images.githubusercontent.com/79659755/111663823-1565ac00-8809-11eb-9ddf-7e7e9ebd0f58.png">
<img width="1678" alt="Screenshot 2021-03-18 at 16 36 37" src="https://user-images.githubusercontent.com/79659755/111663850-1ac2f680-8809-11eb-815c-f57d4723ef4b.png">
<img width="1672" alt="Screenshot 2021-03-18 at 16 35 50" src="https://user-images.githubusercontent.com/79659755/111663867-1e567d80-8809-11eb-82e2-270d3a3b8ba4.png">

**Comment by propertyhive** [comment]
Thanks for getting in touch. I've never seen this before. Certainly sounds like something odd is going on. Is it possible to get WordPress access so I can take a look for myself? You can email this through to info@wp-property-hive.com and I'll take a look.

Steve

**Comment by MB-sites** [comment]
Hi Steve,
Thanks for your reply. I have now added you as an admin.
Thanks for taking a look.
Mike

**Comment by propertyhive** [comment]
Thanks Mike. Is there a reason the menu links to /properties/ which uses shortcodes, instead of the actual search results page /property-search-result/  which gets used when the search form gets submitted. Would it better to just link the menu straight to the search results page?

The former looks to be using shortcodes which, if you're looking to continue doing, will need to be modified as follows:

- Update the search form shortcode to be [property_search_form id="default"]
- Update the [properties] shortcode to be [properties columns="3"]

Let me know your thoughts on the above,

Steve

**Comment by MB-sites** [comment]
Thanks Steve,
I have now changed the menu item to the /property-search-result/ and all works great. Thank you very much for your time and help
