### ISSUE TITLE
PH 1.5.8 Error on Enquiries post in Admin

### ISSUE THREAD

**Issue by johnedwarddalton** [propertyhive/WP-Property-Hive#157]
After updating from PH 1.5.7 to 1.5.8 I am getting the following error notice when I look at an Enquiry post in the Admin area.

Notice: trying to get property 'post_title' of non-object in  ...wp-admin/edit-form-advanced.php on line 738

I haven't yet been able to track down what is causing this
<img width="926" alt="Screenshot 2021-05-16 at 13 10 22" src="https://user-images.githubusercontent.com/3509494/118397019-06a14700-b64a-11eb-8278-96d9a2a3707b.png">

**Comment by propertyhive** [comment]
@johnedwarddalton Thanks for reporting this. You're absolutely right. After much investigation it turns out it's due to an 11 year old issue in WordPress (https://core.trac.wordpress.org/ticket/18408).

I've implemented a workaround and will make this part of the release out later today.

Thanks again! Steve
