### ISSUE TITLE
Image Sizing on Recent Properties

### ISSUE THREAD

**Issue by PaulNWard** [propertyhive/WP-Property-Hive#168]
Hi there, me again, sorry!
How can I make the images in the screenshot Image1 the same height?
I've got [recent_properties per_page="6" columns="3"] 
I know if I use the template assistant and check the Apply CSS to all pages then the images are the same size but it wraps the images so only 2 appear on the line and the 3rd one goes below as in Image2.
![Image1](https://user-images.githubusercontent.com/86826681/127305465-18d03a1e-2743-4d2e-8011-52b65228994f.png)
![Image2](https://user-images.githubusercontent.com/86826681/127305471-f4817cc9-5213-4da9-bd3b-4a03712a8887.png)
Thanks in advance,
Paul

**Comment by propertyhive** [comment]
Hi Paul, 

It looks like the issue is primarily that images are being uploaded/sent with different ratios/heights. Of course a good option to increase consistency is to try and get the images in a standard width/height to begin with.

Failing that, the only other option I can think of, that doesn't result in stretching/squashing the images (which the Template Assistant route will do), is to change the thumbnails so that they are background images instead of <img> tags. We've done this a few times and I've documented this here:

https://gist.github.com/propertyhive/867c71c008c65fe2b0aae7ae55bb2fd6

Let me know your thoughts on the above or if you need any further help,
Steve

**Comment by PaulNWard** [comment]
Hi Steve,

Just done it and that is superb, makes the site look great.
Thanks again for all your help.

Cheers,
Paul

**Comment by PaulNWard** [comment]
Hi Steve,

I have the same issue with the property-images.php. I receive
different size images for a property some are landscape some are portrait
and loads of different pixel heights.
Have you got a code snippet that can force these to be the same height,
width can be anything just need the height to be standard.

Cheers,
Paul
