### ISSUE TITLE
Newly created Commercial properties not showing.

### ISSUE THREAD

**Issue by Smurf1969** [propertyhive/WP-Property-Hive#197]
We've recently started doing Commercial property on the website. Before it was only residential sales.

I've added 2 commercial properties, they are ticked as published and marketing is on.

However, no matter how I search for them, they never show on search results.

Is there something else I need to change?

**Comment by propertyhive** [comment]
@Smurf1969 Do you have a link to the site at all so I can take a look for myself? If not wanting to publish the link publicly please send it through to info@wp-property-hive.com.

Thanks,
Steve

**Comment by propertyhive** [comment]
@Smurf1969 Thanks for sending through access etc. I think the issue is two-fold:

1) The button on the homepage should link to /property-search/?department=commercial. Similarly the lettings one should link to /property-search/?department=residential-lettings
2) the search form hasn't been updated to include commercial:

![Screenshot_8](https://user-images.githubusercontent.com/13717200/187657033-53a6dce8-987f-40be-b222-f36dcfed30ab.png)

Note in the screenshot someone has added a comment of 'Hard Coded Search Form' so I'm assuming someone has done something bespoke here and this might not be manageable from within the WordPress backend. Whoever modified/built this search form will need to add commercial to the 'Looking For' dropdown.

Hope that helps,
Steve
