### ISSUE TITLE
Using Search Results Page

### ISSUE THREAD

**Issue by CTDDeveloperChris** [propertyhive/WP-Property-Hive#200]
Hi,

We have created a website with Property Hive and Elementor and we are having issues with the search results page.

We have created a page called our properties, but we cannot seem to get the search results to display with in Elementor.

Could anyone offer help with the problem we are having here?

Cheers

**Comment by propertyhive** [comment]
Thanks for getting in touch.

We don't currently offer direct Elementor integration for the search results page, only the details page. At present, if you tried to edit this page using Elementor you would indeed get the error.

I've not done it personally but We have seen people get around this in the past by adding a new archive template under 'Templates > Theme Builder > Archive > Add New' so that might be worth a shot. 

Let me know how you get on, 

Steve
