### ISSUE TITLE
Alto Import - Marketing Status not updating

### ISSUE THREAD

**Issue by ctrlaltwebdesign** [propertyhive/WP-Property-Hive#212]
Hi I have recently started using Property Hive with a client and have purchased the import addon to upload their properties via ALTO. The import seems to be working fine other than - not updating the "Marketing Status". This means it is currently showing 70 plus available (on the market) properties when in reality there are only around 30, with the rest that should show SOLD STC or SOLD. 

Any help rectifying this would be a massive help! 

Regards 
Zak

**Comment by propertyhive** [comment]
@ctrlaltwebdesign First to check is whether the status is being set correctly in Property Hive. If you go to 'Property Hive > Properties' in WordPress and find a property you know should be Sold STC, what's the 'availability' showing as?

If it's not not showing as 'Sold STC' like it should, the issue is it's likely not mapped correctly in the import settings.

If still unsure, please feel free to send through WP and examples to info@wp-property-hive.com and I'lll take a look.

Thanks,
Steve
