### ISSUE TITLE
Getting property queries

### ISSUE THREAD

**Issue by algrahamagdigital** [propertyhive/WP-Property-Hive#253]
I'd like the ability to display property settings dynamically such as the property location in a map. I'm using elementor 

![image](https://github.com/user-attachments/assets/ebe6b66c-2799-4ec7-a97b-22bb5dac70e8)

**Comment by propertyhive** [comment]
-- Please reply above this line --


Hello Propertyhive/wp-Property-Hive,

Thank you for reaching out to us. Due to staff holidays and the past
bank holiday weekend, our support team is currently experiencing a
higher volume of enquiries than usual. As a result, there may be a
slight delay in our response times.

Please be assured that we are doing our utmost to address all pending
enquiries as quickly as possible. Your patience and understanding are
greatly appreciated, and we will get back to you at the earliest
opportunity.

Thank you for your continued support.

**Comment by propertyhive** [comment]
You could create custom shortcodes for each of the fields you wish to display. This example below creates a new `[address_street]` shortcode to output the street name:

https://gist.github.com/propertyhive/f42bc53357463d18b9a50e364a4e9cee

Then use this shortcode by selecting 'Shortcode' from the dropdown in your screenshot.
